
# (PART\*) GRÁFICOS AVANZADOS<br>CON ggplot2 {.unnumbered}

# **Visualización avanzada de gráficos**
## Gramática de gráficos: sintaxis de ggplot2
## Visualización por capas

# **Componentes clave de un gráfico con ggplot2**
## Geométricas
## Stats
## Coloreo, rellenado, formas y tipos de línea
## Facetas
## Etiquetas
## Modificando los ejes
## Temas 

# **Creando gráficos**
## Una variable X continua
### Polígonos de frecuencias
### Gráfico de área
### Gráfico de densidad
### Histograma de frecuencias

## Una variable X discreta
### Gráficos de barras
### Gráficos de barras polares
### Gráfios de discrepancia

## Dos variables: X vs Y continuas
### Gráfico de dispersión de puntos
### Gráfico de etiquetas y texto
### Gráficos de densidad 2D

## Dos variables: X discreta vs Y continua
### Gráficos de cajas
### Gráfico de violín

## Dos variables: X vs Y discretas
### Gráficos de conteos
### Gráficos de calor

# **Adicionando Líneas**
## Gráficos de Regresión
## Segmentos y flechas
## Curvas y flechas


# **Gráficos estadísticos semiautomáticos**
## Funciones de `ggpubr`
## Funciones de `ggstatsplot`
## Funciones de `ggcorplot`

# **Exportación de Gráficos**
## Composición de múltiples gráficos
### Utilizando `patchwork`
### Utilizando `ggpubr`
## Exportaci[on] en PNG o JPEG
## Exportación en PDF
